name: Daily Vibe Update

on:
  schedule:
    - cron: '0 6 * * *' # Запуск каждый день в 6:00 утра
  workflow_dispatch: # Чтобы можно было запустить вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python bot.py
        
