name: Daily Vibe Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Обновили версию

      - name: Set up Python
        uses: actions/setup-python@v5 # Обновили версию
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python bot.py
